############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
#tomcat:
#  uri-encoding: UTF-8
#  max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
server:
    port: 8103

spring:
  redis:
    host: 120.46.213.131
    database: 0
    port: 6379
    password: 123456
